### ISSUE TITLE
Add icons as SVG's into project

### ISSUE THREAD

**Issue by discodavey** [elifesciences/enhanced-preprints#140]
# Description

Currently the icons are being brought in via classes using spans. We need to put the icons as SVG's into the project and then place them in the links etc as background images.

# Subtasks

- [ ] Download icons as svg's
- [ ] Add svg's into classes as background images for buttons etc

# Definition of Done

- [ ] All icons as svg's in project and added to classes for buttons etc

**Comment by chris-huggins** [comment]
I can supply SVGs. I think this is worth adding onto the User Story Map so it can be prioritised. For example, it might be easier to do later in case icons change as a result of user testing.

**Comment by discodavey** [comment]
@chris-huggins At the moment they are being placed in by classes and we need to remove the span's so would prefer to put them in sooner. It will be easy to switch them out if user testing suggests a change.

**Comment by chris-huggins** [comment]
[icons.zip](https://github.com/elifesciences/enhanced-preprints/files/9045493/icons.zip)
