### ISSUE TITLE
Add make target for bringing up CouchDB for devs

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints#148]
# Description

Currently, we have some code in repository to use a CouchDB database, but no supporting code to aid developers in using this.

# Tasks

- [x] create a `docker-compose.yaml` that can bring up the CouchDB instance alongside the docker developer container
- [x] create a `Makefile` target to bring up docker compose-based stack for development.

# DoD
- [ ] There is a single `make` target to bring up the application with CouchDB, documented in the README

**Comment by will-byrne** [comment]
Already completed
