### ISSUE TITLE
Style figure caption header and body

### ISSUE THREAD

**Issue by Maelplaine** [elifesciences/enhanced-preprints#154]
# Description

Style figure caption header (i.e. title) and the body (i.e. text)

No need to support edge cases for now i.e. table and references in the caption. 

<img width="813" alt="image" src="https://user-images.githubusercontent.com/39725642/176403663-ed4e3817-280c-42a9-aead-c2791e39cf30.png">

# Documents and Resources

- [ ] [Document 1](https://link.to.the.resource)
- [ ] [Document 2](https://link.to.the.resource)

# Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

# Definition of Done

- [ ] Solution deployed into a production environment and accessible to users.
- [ ] Solution reviewed and approved by all stakeholders.
- [ ] ...
