### ISSUE TITLE
Content Header refactor

### ISSUE THREAD

**Issue by discodavey** [elifesciences/enhanced-preprints#162]
# Description

Refactor of Content Header html/css and accessibility

# Subtasks

- [ ] eLife logo needs text using text indent
- [ ] Content attribute in h1 to be remove as not needed
- [ ] Swap content header div to be header tag
- [ ] Authors list needs aria label
- [ ] Affiliations list needs aria label

# Definition of Done

- [ ] Item 1
- [ ] Item 2
- [ ] ...
