### ISSUE TITLE
Setup files for static HTML examples

### ISSUE THREAD

**Issue by discodavey** [elifesciences/enhanced-preprints#178]
# Description

Setup files for static for the four HTML examples

# Subtasks

- [ ] Export HTML file of the preprint we want to use and duplicate four times using approriate file names
- [ ] export current CSS file or files for the HTML file
- [ ] export current JS file for files for the HTML file
- [ ] Create custom CSS file for the new components
- [ ] Create custom JS file for the new components
