### ISSUE TITLE
Update the server port and message

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints#213]
# Description

Logs:
```
Example app listening on port 3000
```

This is mostly not true, and probably shouldn't be.

# Tasks

- [ ] Change the message so it's not saying example app
- [ ] Set the default port to 8080, or docker-compose to expose port 3000, and change the message to reflect that
- [ ] Make sure to update docker-compose config (if necessary)
- [ ] Update [deployment](https://github.com/elifesciences/elife-flux-test/tree/master/deployments/epp-node-prototype) port (if necessary)

# DoD

- [ ] the startup message is useful to developers.
