### ISSUE TITLE
Add elife dockerhub token to repo secrets

### ISSUE THREAD

**Issue by will-byrne** [elifesciences/enhanced-preprints#26]
## Description
Currently using my personal token which is fine for now but should be switched to the elife one.

## tasks
- [x] Push the container to GHCR instead of dockerhub
- [x] Remove dockerhub token
- [x] Update cluster to pull from GHCR instead of dockerhub

**Comment by scottaubrey** [comment]
We've moved to GHCR instead.
