### ISSUE TITLE
Investigate MongoDB hosting

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints#272]
# Description

# Subtasks

- [x] Install MongoDB operator ([PSMDB](https://www.percona.com/doc/kubernetes-operator-for-psmongodb/index.html)) https://github.com/elifesciences/elife-flux-test/pull/454
- [x] Install MongoDB instance for EPP https://github.com/elifesciences/elife-flux-test/pull/456
- [x] Merge MongoDB repo code into EPP mainline - https://github.com/elifesciences/enhanced-preprints/pull/274
- [x] Fix EPP to allow for user/pass injection - https://github.com/elifesciences/enhanced-preprints/issues/285
- [x] Configure an EPP instance connected to MongoDB
- [x] Benchmark it

# Definition of Done

- [x] The developers understand the difference between MongoDB and CouchDB
- [x] The performance characteristics are understood
- [x] A decision for which database backend to use is able to be made
