### ISSUE TITLE
Switch over to real docmap api

### ISSUE THREAD

**Issue by will-byrne** [elifesciences/enhanced-preprints#31]
## Description
We are currently using a hardcoded docmap with estimated values and the Sciety team have now added Biophysics Colab to their supported groups for docmaps so we can switch to using the real data.

We should ensure that we use a recognisable user agent so Sciety can track our api usage

[List of reviewed articles](https://sciety.org/docmaps/v1/index?publisheraccount=https://sciety.org/groups/biophysics-colab)
[Article](https://sciety.org/docmaps/v1/articles/10.21203/rs.3.rs-955726/v1.docmap.json)
[Docmaps docs](https://sciety.org/docmaps/v1/)

## Tasks
- [x] Replace current hardcoded docmap with one from the Sciety API
- [x] Alter the parsing code to fit (if necessary)
- [x] Add axios call to Sciety Docmaps
- [x] Tests
