### ISSUE TITLE
Replace current css with SASS

### ISSUE THREAD

**Issue by will-byrne** [elifesciences/enhanced-preprints#33]
## Description
The current css implementation was added just for the prototype and should be replaced with SASS to make it easier going forward to implement and maintain our stylesheets.

## Tasks
- [x] move existing CSS to separate file
- [x] serve css file to allow its use in the browser
- [x] re implement styles in SASS
- [x] compile Sass to served file.
- [x] add to docker build
