### ISSUE TITLE
Grid layout on the preprint article page

### ISSUE THREAD

**Issue by Maelplaine** [elifesciences/enhanced-preprints#38]
# Description

### What is the Problem?

Create a grid layout on the preprint article page with columns as [per design](https://projects.invisionapp.com/share/BY12H1HZSGTQ#/screens/465408893_colab-Endorsed-Basic)

### What is the benefit of solving the problem?

The Enhanced Preprint pages will start to have pages that look like preprint pages. Also, we will have a layout to add the missing pages.

### How will we know when the problem has been solved?

The preprint page will have a layout that looks like the layout of the [mockup](https://projects.invisionapp.com/share/BY12H1HZSGTQ#/screens/465408893_colab-Endorsed-Basic)
# Documents and Resources

- [ ] [Design](https://projects.invisionapp.com/share/BY12H1HZSGTQ#/screens/465408893_colab-Endorsed-Basic)

# Tasks

- [x] Check with Dave what he just recently did for the Content Header initiative. He could help
- [x] #43
- [x] #44
- [x] #45

# Definition of Done

- [ ] Solution deployed into a production environment and accessible to users.
- [ ] Solution reviewed and approved by all stakeholders @chris-huggins @Maelplaine 
- [ ] ...
