### ISSUE TITLE
Enable Feature flagging / A/B testing

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints#51]
# Description

### What is the Problem?

One way of experimenting with different layouts would be to enable a feature-flagging system. Then, parts of the system can be selectively turned on and off. This would be an alternative approach to multi-deploys/branches or multiple routes/layouts, but with the added bonus of allowing future feature rollouts to be A/B tested, and for feature testing without managing multiple staging environments, and for rollbacks/feature switch to occur quickly when the need arises

### What is the benefit of solving the problem?

- Build-in capability to selectively turn on or off features during trials/experimental phase.
- Future capability to rollout and rollback out features selectively without proliferation of environments or holding up deployments.
- use Google Analytics to see how effective changes are in a live environment, without having to enable for all users.

### How will we know when the problem has been solved?

We can change the layout of the page via feature flag capabilities, presumably at the moment via query tags or route variables.

### How could we measure the impact or benefit of the solution?

^^^ 

# Documents and Resources

e.g. launchdarkly: https://launchdarkly.com/product/
open source (after quick google search): https://github.com/Unleash/unleash

Note: a simple version that queries a kv store or db can be built fairly simply, but there's a value proposition here vs the maintenance.

# Tasks

- [ ] Investigate feature flagging libraries and services
- [ ] Integrate the library/service

# Definition of Done

- [ ] Solution deployed into a production environment and accessible to users.
- [ ] at least one feature is able to be selectively enabled

**Comment by QueenKraken** [comment]
Checking if this has been completed.
