### ISSUE TITLE
Display an initial review with the preprint content

### ISSUE THREAD

**Issue by NuclearRedeye** [elifesciences/enhanced-preprints#7]
# Description

Next minor goal is to get and display some reviews for the specified article.

# Tasks

- [x] #8
- [x] #22 
- [x] #23 
- [x] #24 
- [x] #30
- [x] #28 

# Definition of Done
- [x] User can navigate to [here](https://epp-node-prototype.elifesciences.org/), select an article and in the header see a link that points towards the 'peer reviews'
- [x] When the user clicks the 'peer reviews' link, it takes the user to a page that displays the entire review content with heading separating the review content. 
- [x] Solution deployed into a staging environment and accessible to users.
- [x] Solution shared with all stakeholders for feedback.
