### ISSUE TITLE
Fixed positioning of the jump-to-menu

### ISSUE THREAD

**Issue by Maelplaine** [elifesciences/enhanced-preprints#82]
# Description

### How could we measure the impact or benefit of the solution?

# Documents and Resources

- [ ] [Document 1](https://link.to.the.resource)
- [ ] [Document 2](https://link.to.the.resource)

# Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

# Definition of Done

- [ ] Solution deployed into a production environment and accessible to users.
- [ ] Solution reviewed and approved by all stakeholders.
- [ ] ...
