### ISSUE TITLE
Hard coded Editors Evaluation with key words on the article page

### ISSUE THREAD

**Issue by Maelplaine** [elifesciences/enhanced-preprints#85]
# Description

# Clarification questions

- Is the board supporting this solution?
**Not sure but let's test this solution**

- Do we place it at the top?
**Yes let's test this position**

- Are we still calling them "Editors Evaluations"?  Or is it "Peer Review Summary" now?
**Andy said he’d speak to the editors about the name next week, but for now let’s call it Evaluation Summary**

### How could we measure the impact or benefit of the solution?

# Documents and Resources

- [ ] [Mockup](https://projects.invisionapp.com/share/4Z12PZBKD6WR#/screens/467140916_just-Hyperlinks-Preprint)
- [ ] [Mockup not to be used](https://projects.invisionapp.com/share/4Z12PZBKD6WR#/screens/467140920_hyperlinks-And-Scale-Preprint)
- [ ] [Document 2](https://link.to.the.resource)

# Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

# Definition of Done

- [ ] Solution deployed into a production environment and accessible to users.
- [ ] Solution reviewed and approved by all stakeholders.
- [ ] ...

**Comment by scottaubrey** [comment]
We may only need to the evaluation summary with the links, not the labels.

Stick with existing colour for the links for now.
