### ISSUE TITLE
Add support for Google Analytics / GTM

### ISSUE THREAD

**Issue by NuclearRedeye** [elifesciences/enhanced-preprints#9]
# Description

We need a means to start gathering metrics so we can understand how users interact with the site and gather data to help us experiment with new layouts and extra data to improve the users overall experience. Googles platform provides us with a fast path to the tools that we need, with Tag Manager, Optimise and Analytics. As such, we should get this enabled on the platform and configure it so that stakeholders can be empowered to start running experiments on the site and gather data to inform decisions moving forward.

# Tasks

- [ ] Is the cookie-less option for GA4 GPDR compliant?
- [ ] Create a GTM account (or add an application to an existing elife one). @Maelplaine 

# GTM Snippets of code to use

Paste this code as high in the <head> of the page as possible:
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5GJVXT2');</script>
<!-- End Google Tag Manager -->

```

Additionally, paste this code immediately after the opening <body> tag:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5GJVXT2"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

# Definition of Done

- [ ] Stakeholders able to view analytics data about visits to the specific pages on the site.
- [ ] Stakeholders able to create triggers to gather more specific data about user interaction with on page elements.
- [ ] Stakeholders able to create and conduct A/B testing to experiment with different layouts and gather appropriate data for analysis.
- [ ] Solution deployed into a staging environment and accessible publicly.
- [ ] Solution shared with stakeholders.

**Comment by NuclearRedeye** [comment]
@scottaubrey @will-byrne I raised this based on the discussion in the review meeting this morning. Can you please add any questions/tasks/etc to the task list and we can break those out into new tickets to add to the board.
Hopefully the goals are clear enough, will refine them more with @chris-huggins and @Maelplaine in the next review meeting.

**Comment by Maelplaine** [comment]
Do you need a GA snippet of code? I can create a new GA property and generate one

**Comment by will-byrne** [comment]
Adding GA to the application is easy, configuring it is not, on Sciety after many attempts to do it ourselves I believe a consultant was hired to do the configuration.

**Comment by NuclearRedeye** [comment]
Thanks for the other @Maelplaine, but I don't think so. I should be able to get everything setup with the guys and I'd quite like to do it myself to build my understanding of analytics.

**Comment by Maelplaine** [comment]
@NuclearRedeye We can pair on this if you want. If you create it yourself, I recommend you to add it as a new property of the "elife-subdomain-...". Please make sure you are an admin. We will need to link this to GTM and create a new property there too. The snippet of code to embed will actually be generated by GTM

**Comment by lsh-0** [comment]
> Is the cookie-less option for GA4 GPDR compliant?

It's likely GA is not compliant with GDPR in general:

* Austria: https://iapp.org/news/a/far-reaching-implications-anticipated-with-austrian-dpas-google-analytics-decision/
* CNIL: https://iapp.org/news/a/cnil-is-latest-authority-to-rule-google-analytics-violates-gdpr/

The trailing comments in the CNIL article are interesting but ultimately it's up to GA to adopt EU-only data processing.

**Comment by scottaubrey** [comment]
This was merged

**Comment by Maelplaine** [comment]
Thanks @scottaubrey
Do you mind if we keep this ticket open until I've confirmed we are receiving data from GA?
I've just linked GTM to GA, and we should be able to see some data soon

**Comment by Maelplaine** [comment]
It looks like it is working
![image](https://user-images.githubusercontent.com/39725642/184109519-9aca7f39-a434-4668-9f0e-2bb8dbdf5999.png)

https://analytics.google.com/analytics/web/#/p326649811/realtime/overview?params=_u..nav%3Dmaui%26_u.comparisonOption%3Ddisabled%26_u.date00%3D20220714%26_u.date01%3D20220810&collectionId=life-cycle

I am going to close this ticket
